### ISSUE TITLE
Header: "Local:" and "Toll free" text aren't editable at back end.  There is no acf at  back end for the contact labels:

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Swan-Valley-Tours#54]
![image](https://cloud.githubusercontent.com/assets/11186313/15775519/d79864f6-29b4-11e6-87f3-afa8987cab18.png)

**Comment by wajahat-titan** [comment]
This was not mentioned in scope to create ACF.
But I've created now for you and its pulled from Theme options
