### ISSUE TITLE
Home - testimonials: Limit the number of lines for the testimonials so as not to break the layout.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Swan-Valley-Tours#60]
![image](https://cloud.githubusercontent.com/assets/11186313/15814340/a77770e6-2bf8-11e6-8400-52c0f0cb84d6.png)

**Comment by wajahat-titan** [comment]
I tried managing by giving height but text was cut off and overlapped. to limit the lines I used Shortentext Function and now issue is solved but displays only one paragraph.
